### ISSUE TITLE
Port over functions from layer-k8s

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/layer-tls#14]
I feel like I might be trying to lift the ca,  client_cert, and server_cert functions from layer-k8s everywhere I use layer-tls. What are your feelings on putting those functions in layer-tls/lib ?

**Comment by mbruzek** [comment]
@jamesbeedy Sorry I missed this comment.  Yes this is a good thing to do as the default location is helpful to nobody.  I need to update k8s to use these new methods.

**Comment by chuckbutler** [comment]
This landed in tlslib
