### ISSUE TITLE
CA Certificate does not get regenerated and deadlocks after first run

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/layer-tls#22]
I've encountered a code path where:

1) CA Certificate was generated on first run
2) I've modified the openssl configuration
3) re-executed the call sequence which wipes easyrsa
4) CA certificate is now no-longer being generated on init-pki, config option has not changed, therefore the CA will never get regenerated

This effectively deadlocks our TLS deployment

**Comment by mbruzek** [comment]
This seems to be a result of the WIP. My understanding is that it is no longer a problem because you took another approach. Please re-open this if you are still having this problem.
