### ISSUE TITLE
set_state('tls.client.authorization.required')

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/layer-tls#36]
I wonder if we shouldn't put this in the base tls layer, and make this a layer configuration option. Its not something that we want to change post deployment, every copy of easyrsa deployed from the derived layer will want the same behavior, and it looks slightly more natural to me than a stray set_state at the top of the python module, which does work.

**Comment by mbruzek** [comment]
@chuckbutler, Yeah I wonder why we didn't do that from the start. I remember talking about this issue but I don't remember why we chose the state.

Some people (I honestly can't remember who) didn't like our other decisions to make something a layer option. Like it was too cumbersome or they didn't agree it was a build time config. I can't remember why either. Perhaps our decision was related to that.

**Comment by chuckbutler** [comment]
i bet it was pr :cop:

**Comment by chuckbutler** [comment]
This appears to have been done https://github.com/juju-solutions/layer-tls/blob/master/reactive/tls.py#L210
