### ISSUE TITLE
The client certificate contains SANs and probably should not

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/layer-tls#39]
The client certificate contains Subject Alternate Names of the leader and should not because a client certificate can be used by other clients who will not have the same IP address.

**Comment by mbruzek** [comment]
I deployed the etcd charm to test this theory, and the client certificate had SANs from the server. 
http://paste.ubuntu.com/18701906/
I don't think the client should include SANs as the client cert/key can be used by any client.

**Comment by mbruzek** [comment]
The kubernetes client certificate generation does not use SANs either. 
https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/generate-cert/make-ca-cert.sh#L102

Based on this I think we should remove the SANs from the client certificate.

**Comment by chuckbutler** [comment]
I'm 👍 to removing any "extras" we're adding here. The cleaner we model the certificates, and closer to upstreams methods we use, the less likely we are to have problems.

Make it so numero uno!
